import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.Date;
import java.util.Scanner;
import static java.time.temporal.ChronoUnit.*;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Karanjit_Singh' at '14/2/17 10:26 AM' with Gradle 3.1
 *
 * @author Karanjit_Singh, @date 14/2/17 10:26 AM
 */
public class remainingDays {


    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        System.out.println("Please enter from date in YYYY-MM-DD format:");
        LocalDate from = LocalDate.parse(sc.nextLine());
        System.out.println("Please enter to date in YYYY-MM-DD format:");
        LocalDate to = LocalDate.parse(sc.nextLine());

        System.out.println("Remaining days from " + from  + " to " + to + " are " + from.until(to, DAYS));

    }

}